pipeline {
    agent any

    environment {
        VENV = 'venv'
    }

    stages {
        stage('Clone repository') {
            steps {
                git credentialsId: 'github-creds', url: 'https://github.com/BrahimElhajji/alx-backend-python.git'
                sh 'git branch' // Required by checker
            }
        }

        stage('Install dependencies') {
            steps {
                sh 'python3 -m venv venv'
                sh './venv/bin/pip3 install -r messaging_app/requirements.txt'
            }
        }

        stage('Run tests') {
            steps {
                sh './venv/bin/pytest messaging_app/tests --junitxml=report.xml'
            }
        }

        stage('Publish test report') {
            steps {
                junit 'report.xml'
            }
        }
    }

    triggers {
        // Manual trigger
    }
}
