# Generated by Django 5.2.1 on 2025-06-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_prent_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='prent_message',
            new_name='parent_message',
        ),
    ]
